######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 17 21:25:31 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fretboard.h fretpanel.h gui.h instrument.h keymap.h midi.h
SOURCES += fretpanel.cpp gui.cpp instrument.cpp keymap.cpp main.cpp midi.cpp

CONFIG += link_pkgconfig
PKGCONFIG += jack
